apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    type: prod
  name: pool-1
spec:
  autoscaling:
    maxNodeCount: 3
    minNodeCount: 1
  clusterRef:
    name: cc-test-k8s
  initialNodeCount: 1
  location: us-central1
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    machineType: e2-standard-4
    metadata:
      disable-legacy-endpoints: "true"
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/devstorage.read_only
    preemptible: false
    serviceAccountRef:
      external: project-service-account@kenthua-test-service-01.iam.gserviceaccount.com