apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: cc-uscentral1
spec:
  ipCidrRange: 10.2.0.0/16
  networkRef:
    name: cc-vpc
  region: us-central1
  secondaryIpRange:
  - ipCidrRange: 10.3.0.0/16
    rangeName: servicesrange
  - ipCidrRange: 10.4.0.0/16
    rangeName: clusterrange