apiVersion: hnc.x-k8s.io/v1alpha2
kind: HNCConfiguration
metadata:
  name: config
spec:
  resources:
  - resource: secrets
    mode: Propagate
  - resource: networkpolicies
    group: networking.k8s.io
    mode: Propagate