apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- base
- api
- cluster
- commerce-frontend
- ui
- commerce-backend
patches:
- path: ignore-deployment-mutation-patch.yaml
  target:
    kind: Deployment
