apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
    client.lifecycle.config.k8s.io/mutation: ignore
    configsync.gke.io/cluster-name-selector: release-k8s    
  labels:
    mesh_id: proj-693281794163
  name: cc-test-k8s
spec:
  addonsConfig:
    configConnectorConfig:
      enabled: true
    dnsCacheConfig:
      enabled: true
    networkPolicyConfig:
      disabled: false
  clusterAutoscaling:
    autoscalingProfile: BALANCED
    enabled: true
    resourceLimits:
    - maximum: 100
      minimum: 10
      resourceType: cpu
    - maximum: 1000
      minimum: 100
      resourceType: memory
  defaultMaxPodsPerNode: 32
  description: A large regional VPC-native cluster set up with special networking
    considerations.
  enableBinaryAuthorization: true
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterSecondaryRangeName: clusterrange
    servicesSecondaryRangeName: servicesrange
  location: us-central1
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: "00:00"
  networkPolicy:
    enabled: true
  networkRef:
    name: cc-vpc
  networkingMode: VPC_NATIVE
  nodeConfig:
    serviceAccountRef:
      external: project-service-account@kenthua-test-service-01.iam.gserviceaccount.com
  nodeLocations:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: cc-test-k8s
  podSecurityPolicyConfig:
    enabled: false
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterGlobalAccessConfig:
      enabled: true
    masterIpv4CidrBlock: 172.16.1.0/28
  releaseChannel:
    channel: REGULAR
  subnetworkRef:
    name: cc-uscentral1
  verticalPodAutoscaling:
    enabled: true
  workloadIdentityConfig:
    identityNamespace: kenthua-test-service-01.svc.id.goog