apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: egress-nat-us-central1
spec:
  natIpAllocateOption: AUTO_ONLY
  region: us-central1
  routerRef:
    name: cc-egress-router-central1
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES