apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: commerce-backend
  name: pod-reader-new
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
